project_id = "eudnclmbrsebofrwkqxy"

[functions.check-pix]
verify_jwt = false

[functions.create-pix]
verify_jwt = false

[functions.get-balance]
verify_jwt = false

[functions.lookup-cep]
verify_jwt = false
